apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  namespace: nithish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-profile
  template:
    metadata:
      labels:
        app: my-profile
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: my-profile-container
          image: nithishacrm3wx2.azurecr.io/my-profile:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: my-profile-service
  namespace: nithish
spec:
  type: LoadBalancer
  selector:
    app: my-profile
  ports:
    - port: 80
      targetPort: 90
